// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHmb8KeFO2gT-NW43bM1fCX1tZppZ6ie8',
    appId: '1:333835514426:web:8194510f55d421d7b8fb03',
    messagingSenderId: '333835514426',
    projectId: 'catalogo-peliculas-a91f3',
    authDomain: 'catalogo-peliculas-a91f3.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-a91f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9o34IM692dEGRhYjELAA9j4aSNuiwb4A',
    appId: '1:333835514426:android:82692324f67fe60cb8fb03',
    messagingSenderId: '333835514426',
    projectId: 'catalogo-peliculas-a91f3',
    storageBucket: 'catalogo-peliculas-a91f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYcJvwv67RrbIyfaHzk7-pDBdeyBFAOuo',
    appId: '1:333835514426:ios:5e1aa4685ffbd2ebb8fb03',
    messagingSenderId: '333835514426',
    projectId: 'catalogo-peliculas-a91f3',
    storageBucket: 'catalogo-peliculas-a91f3.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYcJvwv67RrbIyfaHzk7-pDBdeyBFAOuo',
    appId: '1:333835514426:ios:5e1aa4685ffbd2ebb8fb03',
    messagingSenderId: '333835514426',
    projectId: 'catalogo-peliculas-a91f3',
    storageBucket: 'catalogo-peliculas-a91f3.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHmb8KeFO2gT-NW43bM1fCX1tZppZ6ie8',
    appId: '1:333835514426:web:7d2f0ad3af6618a6b8fb03',
    messagingSenderId: '333835514426',
    projectId: 'catalogo-peliculas-a91f3',
    authDomain: 'catalogo-peliculas-a91f3.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-a91f3.firebasestorage.app',
  );
}
